# Generated by Django 5.2.1 on 2025-10-29 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_number', models.CharField(max_length=100, unique=True)),
                ('cargo_owner', models.CharField(max_length=200)),
                ('storage', models.CharField(max_length=200)),
                ('arrival_date', models.DateField()),
                ('pickup_date', models.DateField()),
                ('arrived_at_storage', models.BooleanField(default=False)),
                ('is_picked_up', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(limit_choices_to={'user_type': 'PORT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
