# Generated by Django 5.2.1 on 2025-10-29 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='cfs',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'CFS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cfs_cargos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='cfs_picked_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargo',
            name='cfs_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='port',
            field=models.ForeignKey(limit_choices_to={'user_type': 'PORT'}, on_delete=django.db.models.deletion.CASCADE, related_name='port_cargos', to=settings.AUTH_USER_MODEL),
        ),
    ]
