# Generated by Django 5.2.1 on 2025-10-29 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cargo_cfs_cargo_cfs_picked_up_cargo_cfs_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_cargos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargo',
            name='scheduled_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
