# Generated by Django 5.2.1 on 2025-10-30 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cargo_driver_cargo_scheduled_pickup_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity', models.PositiveIntegerField(help_text='Total number of containers that can be stored')),
                ('current_capacity', models.PositiveIntegerField(default=0, help_text='Current number of containers stored')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('depot', models.OneToOneField(limit_choices_to={'user_type': 'DEPOT'}, on_delete=django.db.models.deletion.CASCADE, related_name='depot_capacity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Depot Capacities',
            },
        ),
    ]
